export interface Playlist {
    id: string,
    name: string,
    description: string,
    owner: any,
    collaborative: boolean,
    href: string,
    images: Array<any>,
    public: boolean,
    uri: string,
    primary_color: any,
    external_urls: any,
    snapshot_id: string,
    tracks: any,
    type: string,
}

export interface Track {
    id: string,
    name: string,
    album: any,
    artists: Array<any>,
    available_markets: Array<any>,
    disc_number: number,
    duration_ms: 211653,
    eppisode: boolean,
    explicit: boolean,
    external_ids: any,
    external_urls: any,
    href: string,
    is_local: boolean,
    popularity: number,
    preview_url?: string,
    track: boolean,
    track_number: number,
    type: string,
    uri: string
}